export type Stage = 'Coachella' | 'Outdoor' | 'Sahara' | 'Mojave' | 'Gobi' | 'Sonora' | 'Yuma' | 'Do LaB' | 'Heineken House' | 'Quasar' | 'TBA'
export type Day = 'Friday' | 'Saturday' | 'Sunday' | 'TBA'
export type Genre = 'Pop' | 'Hip-Hop' | 'Electronic' | 'Rock' | 'Indie' | 'R&B' | 'Latin' | 'Alternative' | 'Dance' | 'Experimental' | 'Folk' | 'Punk' | 'Metal' | 'K-Pop' | 'J-Pop' | 'Afrobeats' | 'Classical' | 'Country' | 'Mixed'

export interface Artist {
  id: string
  name: string
  stage: Stage
  day: Day
  genre: Genre
  emoji: string
}

export const artists: Artist[] = [
  { id: 'sabrina-carpenter', name: 'Sabrina Carpenter', stage: 'Coachella', day: 'Friday', genre: 'Pop', emoji: '🎤' },
  { id: 'justin-bieber', name: 'Justin Bieber', stage: 'Coachella', day: 'Saturday', genre: 'Pop', emoji: '🎤' },
  { id: 'karol-g', name: 'KAROL G', stage: 'Coachella', day: 'Sunday', genre: 'Latin', emoji: '🎤' },
  { id: 'anyma', name: 'Anyma', stage: 'Outdoor', day: 'Saturday', genre: 'Electronic', emoji: '🎹' },
  { id: 'the-xx', name: 'the XX', stage: 'Outdoor', day: 'Friday', genre: 'Indie', emoji: '🎸' },
  { id: 'the-strokes', name: 'The Strokes', stage: 'Coachella', day: 'Friday', genre: 'Rock', emoji: '🎸' },
  { id: 'young-thug', name: 'Young Thug', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'bigbang', name: 'BIGBANG', stage: 'TBA', day: 'TBA', genre: 'K-Pop', emoji: '🎤' },
  { id: 'addison-rae', name: 'Addison Rae', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'nine-inch-noize', name: 'Nine Inch Noize', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'and-friends', name: '&friends', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: '54-ultra', name: '54 Ultra', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'adriatique', name: 'Adriatique', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'alex-g', name: 'Alex G', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'armin-van-buuren-adam-beyer', name: 'Armin van Buuren × Adam Beyer', stage: 'Sahara', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'arodes', name: 'Arodes', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'azzecca', name: 'AZZECCA', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'bedouin', name: 'Bedouin', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'ben-sterling', name: 'Ben Sterling', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'bini', name: 'BINI', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'black-flag', name: 'Black Flag', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'blondshell', name: 'Blondshell', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎸' },
  { id: 'blood-orange', name: 'Blood Orange', stage: 'TBA', day: 'TBA', genre: 'R&B', emoji: '🎵' },
  { id: 'bob-baker-marionettes', name: 'Bob Baker Marionettes', stage: 'TBA', day: 'TBA', genre: 'Experimental', emoji: '🎪' },
  { id: 'boys-noize', name: 'Boys Noize', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'bunt', name: 'BUNT.', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'cachirula-loojan', name: 'Cachirula & Loojan', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'carlita-josh-baker', name: 'Carlita x Josh Baker', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'carolina-durante', name: 'Carolina Durante', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'central-cee', name: 'Central Cee', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'ceremony', name: 'Ceremony', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'chloe-caillet-rossi', name: 'Chloé Caillet x Rossi.', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'clipse', name: 'Clipse', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'cmat', name: 'CMAT', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'cobrah', name: 'COBRAH', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'creepy-nuts', name: 'Creepy Nuts', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'dabeull', name: 'Dabeull', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'david-byrne', name: 'David Byrne', stage: 'TBA', day: 'TBA', genre: 'Rock', emoji: '🎸' },
  { id: 'davido', name: 'Davido', stage: 'TBA', day: 'TBA', genre: 'Afrobeats', emoji: '🎵' },
  { id: 'devo', name: 'Devo', stage: 'TBA', day: 'TBA', genre: 'Rock', emoji: '🎸' },
  { id: 'die-spitz', name: 'Die Spitz', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'dijon', name: 'Dijon', stage: 'TBA', day: 'TBA', genre: 'R&B', emoji: '🎵' },
  { id: 'disclosure', name: 'Disclosure', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'drain', name: 'DRAIN', stage: 'TBA', day: 'TBA', genre: 'Metal', emoji: '🎸' },
  { id: 'duke-dumont', name: 'Duke Dumont', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'ecca-vandal', name: 'Ecca Vandal', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎸' },
  { id: 'ethel-cain', name: 'Ethel Cain', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎤' },
  { id: 'fakemink', name: 'fakemink', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'febuary', name: 'Febuary', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'fka-twigs', name: 'FKA twigs', stage: 'TBA', day: 'TBA', genre: 'Experimental', emoji: '🎤' },
  { id: 'fleshwater', name: 'Fleshwater', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎸' },
  { id: 'flowerovlove', name: 'flowerovlove', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'foster-the-people', name: 'Foster the People', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'freak-slug', name: 'Freak Slug', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'french-police', name: 'French Police', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'fujii-kaze', name: 'Fujii Kaze', stage: 'TBA', day: 'TBA', genre: 'J-Pop', emoji: '🎵' },
  { id: 'geese', name: 'Geese', stage: 'TBA', day: 'TBA', genre: 'Rock', emoji: '🎸' },
  { id: 'genesi', name: 'GENESI', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'gigi-perez', name: 'Gigi Perez', stage: 'TBA', day: 'TBA', genre: 'Folk', emoji: '🎸' },
  { id: 'giveon', name: 'GIVĒON', stage: 'TBA', day: 'TBA', genre: 'R&B', emoji: '🎵' },
  { id: 'glitterer', name: 'Glitterer', stage: 'TBA', day: 'TBA', genre: 'Rock', emoji: '🎸' },
  { id: 'gordo', name: 'Gordo', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'green-velvet-ayybo', name: 'Green Velvet × AYYBO', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'groove-armada', name: 'Groove Armada', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'hamdi', name: 'Hamdi', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'holly-humberstone', name: 'Holly Humberstone', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'hot-mulligan', name: 'Hot Mulligan', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'hugel', name: 'HUGEL', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'iggy-pop', name: 'Iggy Pop', stage: 'TBA', day: 'TBA', genre: 'Rock', emoji: '🎸' },
  { id: 'interpol', name: 'Interpol', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'jane-remover', name: 'Jane Remover', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎸' },
  { id: 'jessica-brankka', name: 'Jessica Brankka', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'joost', name: 'Joost', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'joyce-manor', name: 'Joyce Manor', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'kaskade', name: 'Kaskade', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'katseye', name: 'KATSEYE', stage: 'TBA', day: 'TBA', genre: 'K-Pop', emoji: '🎤' },
  { id: 'kettama', name: 'Kettama', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'labrinth', name: 'Labrinth', stage: 'TBA', day: 'TBA', genre: 'R&B', emoji: '🎵' },
  { id: 'lambrini-girls', name: 'Lambrini Girls', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'laufey', name: 'Laufey', stage: 'TBA', day: 'TBA', genre: 'Folk', emoji: '🎻' },
  { id: 'le-yora', name: 'LE YORA', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'levity', name: 'Levity', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'little-simz', name: 'Little Simz', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'los-hermanos-flores', name: 'Los Hermanos Flores', stage: 'TBA', day: 'TBA', genre: 'Latin', emoji: '🎵' },
  { id: 'los-retros', name: 'Los Retros', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'luisa-sonza', name: 'Luísa Sonza', stage: 'TBA', day: 'TBA', genre: 'Latin', emoji: '🎤' },
  { id: 'lykke-li', name: 'Lykke Li', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎤' },
  { id: 'mahmut-orhan', name: 'Mahmut Orhan', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'major-lazer', name: 'Major Lazer', stage: 'TBA', day: 'TBA', genre: 'Dance', emoji: '🎹' },
  { id: 'marlon-hoffstadt', name: 'Marlon Hoffstadt', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'max-dean-luke-dean', name: 'Max Dean x Luke Dean', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'max-styler', name: 'Max Styler', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'mind-enterprises', name: 'Mind Enterprises', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'moby', name: 'Moby', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'mochakk', name: 'Mochakk', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'model-actriz', name: 'Model/Actriz', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎸' },
  { id: 'mestiza', name: 'MËSTIZA', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'newdad', name: 'NewDad', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'ninajirachi', name: 'Ninajirachi', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'noga-erez', name: 'Noga Erez', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'oklou', name: 'Oklou', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'pinkpantheress', name: 'PinkPantheress', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'prospa', name: 'Prospa', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'rezz', name: 'REZZ', stage: 'Sahara', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'riordan', name: 'Riordan', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'royel-otis', name: 'Royel Otis', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'rusowsky', name: 'rusowsky', stage: 'TBA', day: 'TBA', genre: 'Latin', emoji: '🎵' },
  { id: 'royksopp', name: 'Röyksopp', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'roz', name: 'RØZ', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'sahar-z', name: 'Sahar Z', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'samia', name: 'Samia', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'sexyy-red', name: 'Sexyy Red', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'slayyyter', name: 'Slayyyter', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'solomun', name: 'Solomun', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'sombr', name: 'SOMBR', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'sosa', name: 'SOSA', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'subtronics', name: 'Subtronics', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'suicidal-tendencies', name: 'Suicidal Tendencies', stage: 'TBA', day: 'TBA', genre: 'Metal', emoji: '🎸' },
  { id: 'swae-lee', name: 'Swae Lee', stage: 'TBA', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'taemin', name: 'Taemin', stage: 'TBA', day: 'TBA', genre: 'K-Pop', emoji: '🎤' },
  { id: 'teddy-swims', name: 'Teddy Swims', stage: 'TBA', day: 'TBA', genre: 'R&B', emoji: '🎵' },
  { id: 'the-chats', name: 'The Chats', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'the-rapture', name: 'The Rapture', stage: 'TBA', day: 'TBA', genre: 'Dance', emoji: '🎸' },
  { id: 'the-two-lips', name: 'The Two Lips', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'tomora', name: 'Tomora', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'turnstile', name: 'Turnstile', stage: 'TBA', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'wednesday', name: 'Wednesday', stage: 'TBA', day: 'TBA', genre: 'Alternative', emoji: '🎸' },
  { id: 'wet-leg', name: 'Wet Leg', stage: 'TBA', day: 'TBA', genre: 'Indie', emoji: '🎸' },
  { id: 'whatmore', name: 'WHATMORE', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'whomadewho', name: 'WhoMadeWho', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'worship', name: 'Worship', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'yamagucci', name: 'Yamagucci', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'youna', name: 'Youna', stage: 'TBA', day: 'TBA', genre: 'Pop', emoji: '🎤' },
  { id: 'yousuke-yukimatsu', name: '¥ØU$UK€ ¥UK1MAT$U', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'zulan', name: 'ZULAN', stage: 'TBA', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'andruss', name: 'Andruss', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'coi-leray', name: 'Coi Leray', stage: 'Heineken House', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'joshwa', name: 'Joshwa', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'kryptogram', name: 'Kryptogram', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'less-than-jake', name: 'Less Than Jake', stage: 'Heineken House', day: 'TBA', genre: 'Punk', emoji: '🎸' },
  { id: 'mild-minds', name: 'Mild Minds', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'motion-city-soundtrack', name: 'Motion City Soundtrack', stage: 'Heineken House', day: 'TBA', genre: 'Rock', emoji: '🎸' },
  { id: 'niiko-x-swae', name: 'Niiko X Swae', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'nimino', name: 'Nimino', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'oskar-med-k', name: 'Oskar Med K', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'redke', name: 'REDKE', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'robin-schulz', name: 'Robin Schulz', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'sander-kleinenberg', name: 'Sander Kleinenberg', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'wale', name: 'Wale', stage: 'Heineken House', day: 'TBA', genre: 'Hip-Hop', emoji: '🎤' },
  { id: 'zerb', name: 'Zerb', stage: 'Heineken House', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'sean-paul', name: 'Sean Paul', stage: 'Heineken House', day: 'Friday', genre: 'Dance', emoji: '🎤' },
  { id: '1tbsp', name: '1tbsp', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'andhim', name: 'Andhim', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'andy-c', name: 'Andy C', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'anfisa-letyago', name: 'Anfisa Letyago', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'baalti', name: 'Baalti', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'baby-j', name: 'Baby J', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'brunello', name: 'Brunello', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'bullet-tooth', name: 'Bullet Tooth', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'cincity', name: 'Cincity', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'deer-jade', name: 'Deer Jade', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'effin', name: 'Effin', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'fifi', name: 'Fifi', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'jackie-hollander', name: 'Jackie Hollander', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'jazzy', name: 'Jazzy', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'jigitz', name: 'Jigitz', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'lumia', name: 'Lumia', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'mcr-t', name: 'MCR-T', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'omar-plus', name: 'Omar+', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'omnom', name: 'Omnom', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'poolside-daytime-disco', name: "Poolside's Daytime Disco", stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'roddy-lima', name: 'Roddy Lima', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'soraya', name: 'Soraya', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'soul-purpose', name: 'Soul Purpose', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'starjunk-95', name: 'Starjunk 95', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
  { id: 'tinashe-dj-set', name: 'Tinashe (DJ Set)', stage: 'Do LaB', day: 'TBA', genre: 'R&B', emoji: '🎵' },
  { id: 'whethan', name: 'Whethan', stage: 'Do LaB', day: 'TBA', genre: 'Electronic', emoji: '🎹' },
]

export function getArtistsByDay(day: Day): Artist[] {
  return artists.filter(a => a.day === day)
}

export function getArtistsByStage(stage: Stage): Artist[] {
  return artists.filter(a => a.stage === stage)
}

export function searchArtists(query: string): Artist[] {
  const q = query.toLowerCase()
  return artists.filter(a => a.name.toLowerCase().includes(q))
}
