export interface FestivalArtist {
  id: string
  name: string
  stage: string
  day: string
  headliner?: boolean
}

export interface Festival {
  id: string
  name: string
  shortName: string
  city: string
  state: string
  dates: string
  days: string[]
  dayDates: Record<string, string>   // { friday: 'Jun 13', ... }
  stages: string[]
  emoji: string
  headliners: string[]               // preview list for the picker card
  artists: FestivalArtist[]
}

// Per-artist stage assignments aren't published by either festival until set
// times drop closer to the event, so every artist below is tagged 'Stage TBA'.

// ── Lollapalooza 2026 ─────────────────────────────────────────────────────────
// Full day-by-day lineup as announced on the official admat (lollapalooza.com/lineup).

const LOLLAPALOOZA: Festival = {
  id: 'lollapalooza-2026',
  name: 'Lollapalooza 2026',
  shortName: 'Lolla',
  city: 'Chicago',
  state: 'IL',
  dates: 'Jul 30 – Aug 2, 2026',
  days: ['thursday', 'friday', 'saturday', 'sunday'],
  dayDates: { thursday: 'Jul 30', friday: 'Jul 31', saturday: 'Aug 1', sunday: 'Aug 2' },
  stages: ['Stage TBA'],
  emoji: '🌭',
  headliners: ['Charli XCX', 'Lorde', 'Tate McRae'],
  artists: [
    // ── Thursday, Jul 30 ──
    { id: 'lolla-lorde',                 name: 'Lorde',                             stage: 'Stage TBA', day: 'thursday', headliner: true },
    { id: 'lolla-john-summit',           name: 'John Summit',                       stage: 'Stage TBA', day: 'thursday', headliner: true },
    { id: 'lolla-sombr',                 name: 'Sombr',                             stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-empire-of-the-sun',     name: 'Empire of the Sun',                 stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-wet-leg',               name: 'Wet Leg',                           stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-worship',               name: 'Worship',                           stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-blood-orange',          name: 'Blood Orange',                      stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-5-seconds-of-summer',   name: '5 Seconds of Summer',               stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-kettama',               name: 'Kettama',                           stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-viagra-boys',           name: 'Viagra Boys',                       stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-audrey-hobert',         name: 'Audrey Hobert',                     stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-snow-strippers',        name: 'Snow Strippers',                    stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-boris-brejcha',         name: 'Boris Brejcha',                     stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-paris-paloma',          name: 'Paris Paloma',                      stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-little-simz',           name: 'Little Simz',                       stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-cmat',                  name: 'CMAT',                              stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-boys-noize',            name: 'Boys Noize',                        stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-between-friends',       name: 'Between Friends',                   stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-mph',                   name: 'MPH',                               stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-amble',                 name: 'Amble',                             stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-kingfishr',             name: 'Kingfishr',                         stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-ninajirachi',           name: 'Ninajirachi',                       stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-haute-and-freddy',      name: 'Haute & Freddy',                    stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-bella-kay',             name: 'Bella Kay',                         stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-marlon-funaki',         name: 'Marlon Funaki',                     stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-devault',               name: 'Devault',                           stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-sb19',                  name: 'SB19',                              stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-ecca-vandal',           name: 'Ecca Vandal',                       stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-bad-nerves',            name: 'Bad Nerves',                        stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-asha-banks',            name: 'Asha Banks',                        stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-faouzia',               name: 'Faouzia',                           stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-evening-elephants',     name: 'Evening Elephants',                 stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-pearly-drops',          name: 'Pearly Drops',                      stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-bixby',                 name: 'Bixby',                             stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-penelope-road',         name: 'Penelope Road',                     stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-know-good',             name: 'Know Good',                         stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-elizabeth-nichols',     name: 'Elizabeth Nichols',                 stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-klo',                   name: 'KLO',                               stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-the-braymores',         name: 'The Braymores',                     stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-chalk',                 name: 'Chalk',                             stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-simon-grossmann',       name: 'Simon Grossmann',                   stage: 'Stage TBA', day: 'thursday' },
    { id: 'lolla-kim-theory',            name: 'Kim Theory',                        stage: 'Stage TBA', day: 'thursday' },

    // ── Friday, Jul 31 ──
    { id: 'lolla-charli-xcx',            name: 'Charli XCX',                        stage: 'Stage TBA', day: 'friday', headliner: true },
    { id: 'lolla-smashing-pumpkins',     name: 'The Smashing Pumpkins',             stage: 'Stage TBA', day: 'friday', headliner: true },
    { id: 'lolla-lil-uzi-vert',          name: 'Lil Uzi Vert',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-yungblud',              name: 'Yungblud',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-major-lazer',           name: 'Major Lazer',                       stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-not-for-radio',         name: 'Not For Radio',                     stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-zara-larsson',          name: 'Zara Larsson',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-freddie-gibbs',         name: 'Freddie Gibbs',                     stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-suki-waterhouse',       name: 'Suki Waterhouse',                   stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-i-dle',                 name: 'I-DLE',                             stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-mustard',               name: 'Mustard',                           stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-oklou',                 name: 'Oklou',                             stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-horsegiirl',            name: 'Horsegiirl',                        stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-the-story-so-far',      name: 'The Story So Far',                  stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-loathe',                name: 'Loathe',                            stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-nettspend',             name: 'Nettspend',                         stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-sidepiece',             name: 'Sidepiece',                         stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-skye-newman',           name: 'Skye Newman',                       stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-notion',                name: 'Notion',                            stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-roz',                   name: 'RØZ',                               stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-balu-brigada',          name: 'Balu Brigada',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-lyny',                  name: 'LYNY',                              stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-mother-mother',         name: 'Mother Mother',                     stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-julia-wolf',            name: 'Julia Wolf',                        stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-slayyyter',             name: 'Slayyyter',                         stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-claire-rosinkranz',     name: 'Claire Rosinkranz',                 stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-54-ultra',              name: '54 Ultra',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-high-vis',              name: 'High Vis',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-finn-wolfhard',         name: 'Finn Wolfhard',                     stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-avello',                name: 'Avello',                            stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-partyof2',              name: 'Partyof2',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-the-army-the-navy',     name: 'The Army, The Navy',                stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-love-spells',           name: 'Love Spells',                       stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-ella-red',              name: 'Ella Red',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-paloma-morphy',         name: 'Paloma Morphy',                     stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-day-we-ran',            name: 'Day We Ran',                        stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-ivri',                  name: 'Ivri',                              stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-ella-boh',              name: 'Ella Boh',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-bradeazy',              name: 'Bradeazy',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-emi-grace',             name: 'Emi Grace',                         stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-beno',                  name: 'Beno',                              stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-chicago-made',          name: 'Chicago Made',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-valencia-grace',        name: 'Valencia Grace',                    stage: 'Stage TBA', day: 'friday' },
    { id: 'lolla-whitney-whitney',       name: 'Whitney Whitney',                   stage: 'Stage TBA', day: 'friday' },

    // ── Saturday, Aug 1 ──
    { id: 'lolla-olivia-dean',           name: 'Olivia Dean',                       stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'lolla-jennie',                name: 'Jennie',                            stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'lolla-the-neighbourhood',     name: 'The Neighbourhood',                 stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-ethel-cain',            name: 'Ethel Cain',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-disco-lines',           name: 'Disco Lines',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-leon-thomas',           name: 'Leon Thomas',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-clipse',                name: 'Clipse',                            stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-geese',                 name: 'Geese',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-alison-wonderland',     name: 'Alison Wonderland',                 stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-dj-trixie-mattel',      name: 'DJ Trixie Mattel',                  stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-bbnos',                 name: 'BBNOS',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-kwn',                   name: 'KWN',                               stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-sienna-spiro',          name: 'Sienna Spiro',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-max-styler',            name: 'Max Styler',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-spacey-jane',           name: 'Spacey Jane',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-wolf-alice',            name: 'Wolf Alice',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-whethan',               name: 'Whethan',                           stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-cortis',                name: 'Cortis',                            stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-cameron-whitcomb',      name: 'Cameron Whitcomb',                  stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-ayybo',                 name: 'Ayybo',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-khamari',               name: 'Khamari',                           stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-quadeca',               name: 'Quadeca',                           stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-momma',                 name: 'Momma',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-frost-children',        name: 'Frost Children',                    stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-goldie-boutilier',      name: 'Goldie Boutilier',                  stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-die-spitz',             name: 'Die Spitz',                         stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-lucy-bedroque',         name: 'Lucy Bedroque',                     stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-omnom',                 name: 'Omnom',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-jim-legxacy',           name: 'Jim Legxacy',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-chezile',               name: 'Chezile',                           stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-jae-stephens',          name: 'Jae Stephens',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-ryman',                 name: 'Ryman',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-villanelle',            name: 'Villanelle',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-sunday-1994',           name: 'Sunday (1994)',                     stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-mc4d',                  name: 'MC4D',                              stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-chace',                 name: 'Chace',                             stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-calder-allen',          name: 'Calder Allen',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-nat-myers',             name: 'Nat Myers',                         stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-ink',                   name: 'Ink',                               stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-peace-control',         name: 'Peace Control',                     stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-the-creekers',          name: 'The Creekers',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-next-of-kin',           name: 'Next of Kin',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'lolla-cyso',                  name: 'Chicago Youth Symphony Orchestra',  stage: 'Stage TBA', day: 'saturday' },

    // ── Sunday, Aug 2 ──
    { id: 'lolla-tate-mcrae',            name: 'Tate McRae',                        stage: 'Stage TBA', day: 'sunday', headliner: true },
    { id: 'lolla-the-xx',                name: 'The xx',                            stage: 'Stage TBA', day: 'sunday', headliner: true },
    { id: 'lolla-turnstile',             name: 'Turnstile',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-beabadoobee',           name: 'Beabadoobee',                       stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-aespa',                 name: 'Aespa',                             stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-the-chainsmokers',      name: 'The Chainsmokers',                  stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-muna',                  name: 'Muna',                              stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-hot-mulligan',          name: 'Hot Mulligan',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-yoasobi',               name: 'Yoasobi',                           stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-ado',                   name: 'Ado',                               stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-jade',                  name: 'Jade',                              stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-eli-brown',             name: 'Eli Brown',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-duke-dumont',           name: 'Duke Dumont',                       stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-fakemink',              name: 'Fakemink',                          stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-dombresky',             name: 'Dombresky',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-monaleo',               name: 'Monaleo',                           stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-adela',                 name: 'Adéla',                             stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-riordan',               name: 'Riordan',                           stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-wunderhorse',           name: 'Wunderhorse',                       stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-amber-mark',            name: 'Amber Mark',                        stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-westend',               name: 'Westend',                           stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-destin-conrad',         name: 'Destin Conrad',                     stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-inji',                  name: 'Inji',                              stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-waylon-wyatt',          name: 'Waylon Wyatt',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-water-from-your-eyes',  name: 'Water From Your Eyes',              stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-los-retros',            name: 'Los Retros',                        stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-vandelux',              name: 'Vandelux',                          stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-new-constellations',    name: 'New Constellations',                stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-cruz-beckham-breakers', name: 'Cruz Beckham and the Breakers',     stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-the-bends',             name: 'The Bends',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-after',                 name: 'After',                             stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-whatmore',              name: 'Whatmore',                          stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-porch-light',           name: 'Porch Light',                       stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-easy-honey',            name: 'Easy Honey',                        stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-jackie-hollander',      name: 'Jackie Hollander',                  stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-stella-lefty',          name: 'Stella Lefty',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-justine-skye',          name: 'Justine Skye',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-will-swinton',          name: 'Will Swinton',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-sunshine',              name: 'Sunshine',                          stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-case-oats',             name: 'Case Oats',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-surfing-for-daisy',     name: 'Surfing For Daisy',                 stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-snacktime',             name: 'Snacktime',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'lolla-zack-martino',          name: 'Zack Martino',                      stage: 'Stage TBA', day: 'sunday' },
  ],
}

// ── Outside Lands 2026 ────────────────────────────────────────────────────────
// Full day-by-day lineup as announced on the official daily-lineup poster (sfoutsidelands.com/lineup).

const OUTSIDE_LANDS: Festival = {
  id: 'outside-lands-2026',
  name: 'Outside Lands 2026',
  shortName: 'Outside Lands',
  city: 'San Francisco',
  state: 'CA',
  dates: 'Aug 7–9, 2026',
  days: ['friday', 'saturday', 'sunday'],
  dayDates: { friday: 'Aug 7', saturday: 'Aug 8', sunday: 'Aug 9' },
  stages: ['Stage TBA'],
  emoji: '🌉',
  headliners: ['Charli XCX', 'The Strokes', 'Rüfüs Du Sol'],
  artists: [
    // ── Friday, Aug 7 ──
    { id: 'osl-charli-xcx',            name: 'Charli XCX',                       stage: 'Stage TBA', day: 'friday', headliner: true },
    { id: 'osl-turnstile',             name: 'Turnstile',                        stage: 'Stage TBA', day: 'friday', headliner: true },
    { id: 'osl-griztronics',           name: 'Griztronics (Subtronics + Griz)',  stage: 'Stage TBA', day: 'friday', headliner: true },
    { id: 'osl-labrinth',              name: 'Labrinth',                         stage: 'Stage TBA', day: 'friday', headliner: true },
    { id: 'osl-glorilla',              name: 'GloRilla',                         stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-geese',                 name: 'Geese',                            stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-clipse',                name: 'Clipse',                           stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-modest-mouse',          name: 'Modest Mouse',                     stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-wet-leg',               name: 'Wet Leg',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-tinashe',               name: 'Tinashe',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-sierra-ferrell',        name: 'Sierra Ferrell',                   stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-hyperbeam',             name: 'Hyperbeam (Odd Mob + Omnom)',      stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-the-story-so-far',      name: 'The Story So Far',                 stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-yousuke-yukimatsu',     name: '¥ØU$UK€ ¥UKIMAT$U',                stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-ki-ki',                 name: 'KI/KI',                            stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-durand-bernarr',        name: 'Durand Bernarr',                   stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-alleycvt',              name: 'Alleycvt',                         stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-die-spitz',             name: 'Die Spitz',                        stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-mph',                   name: 'MPH',                              stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-goldie-boutilier',      name: 'Goldie Boutilier',                 stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-dylan-brady',           name: 'Dylan Brady',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-tobiahs',               name: 'Tobiahs',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-billie-marten',         name: 'Billie Marten',                    stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-faouzia',               name: 'Faouzia',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-bad-nerves',            name: 'Bad Nerves',                       stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-luke-alessi',           name: 'Luke Alessi',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-chezile',               name: 'Chezile',                          stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-sawyer-hill',           name: 'Sawyer Hill',                      stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-nezza',                 name: 'Nezza',                            stage: 'Stage TBA', day: 'friday' },
    { id: 'osl-vertigo',               name: 'Vertigo',                          stage: 'Stage TBA', day: 'friday' },

    // ── Saturday, Aug 8 ──
    { id: 'osl-the-strokes',           name: 'The Strokes',                      stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'osl-the-xx',                name: 'The xx',                           stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'osl-djo',                   name: 'Djo',                              stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'osl-dijon',                 name: 'Dijon',                            stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'osl-pinkpantheress',        name: 'PinkPantheress',                   stage: 'Stage TBA', day: 'saturday', headliner: true },
    { id: 'osl-ethel-cain',            name: 'Ethel Cain',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-lucy-dacus',            name: 'Lucy Dacus',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-malcolm-todd',          name: 'Malcolm Todd',                     stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-lane-8',                name: 'Lane 8',                           stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-snow-strippers',        name: 'Snow Strippers',                   stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-its-murph',             name: "It's Murph",                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-audrey-hobert',         name: 'Audrey Hobert',                    stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-ben-bohmer',            name: 'Ben Böhmer',                       stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-dj-trixie-mattel',      name: 'DJ Trixie Mattel',                 stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-laszewo',               name: 'Łaszewo',                          stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-sienna-spiro',          name: 'Sienna Spiro',                     stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-sultan-shepard',        name: 'Sultan + Shepard',                 stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-silvana-estrada',       name: 'Silvana Estrada',                  stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-haute-and-freddy',      name: 'Haute & Freddy',                   stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-yard-act',              name: 'Yard Act',                         stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-wunderhorse',           name: 'Wunderhorse',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-camoufly',              name: 'Camoufly',                         stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-bandalos-chinos',       name: 'Bandalos Chinos',                  stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-after',                 name: 'After',                            stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-rio-kosta',             name: 'Rio Kosta',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-automatic',             name: 'Automatic',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-racing-mount-pleasant', name: 'Racing Mount Pleasant',            stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-bad-juuju',             name: 'Bad Juuju',                        stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-1-800-girls',           name: '1-800 Girls',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-red-leather',           name: 'Red Leather',                      stage: 'Stage TBA', day: 'saturday' },
    { id: 'osl-ryman',                 name: 'Ryman',                            stage: 'Stage TBA', day: 'saturday' },

    // ── Sunday, Aug 9 ──
    { id: 'osl-rufus-du-sol',          name: 'Rüfüs Du Sol',                     stage: 'Stage TBA', day: 'sunday', headliner: true },
    { id: 'osl-baby-keem',             name: 'Baby Keem',                        stage: 'Stage TBA', day: 'sunday', headliner: true },
    { id: 'osl-empire-of-the-sun',     name: 'Empire of the Sun',                stage: 'Stage TBA', day: 'sunday', headliner: true },
    { id: 'osl-death-cab-for-cutie',   name: 'Death Cab for Cutie',              stage: 'Stage TBA', day: 'sunday', headliner: true },
    { id: 'osl-disco-lines',           name: 'Disco Lines',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-mariah-the-scientist',  name: 'Mariah the Scientist',             stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-not-for-radio',         name: 'Not For Radio',                    stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-boris-brejcha',         name: 'Boris Brejcha',                    stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-the-temper-trap',       name: 'The Temper Trap',                  stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-jade',                  name: 'Jade',                             stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-kwn',                   name: 'KWN',                              stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-boys-noize',            name: 'Boys Noize',                       stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-destin-conrad',         name: 'Destin Conrad',                    stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-kingfishr',             name: 'Kingfishr',                        stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-balu-brigada',          name: 'Balu Brigada',                     stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-frost-children',        name: 'Frost Children',                   stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-miss-monique',          name: 'Miss Monique',                     stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-carlita',               name: 'Carlita',                          stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-amble',                 name: 'Amble',                            stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-momma',                 name: 'Momma',                            stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-infinity-song',         name: 'Infinity Song',                    stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-sports',                name: 'Sports',                           stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-marlon-funaki',         name: 'Marlon Funaki',                    stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-night-tapes',           name: 'Night Tapes',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-x-club',                name: 'X Club.',                          stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-jim-legxacy',           name: 'Jim Legxacy',                      stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-sosocamo',              name: 'Sosocamo',                         stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-day-we-ran',            name: 'Day We Ran',                       stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-cruz-beckham',          name: 'Cruz Beckham',                     stage: 'Stage TBA', day: 'sunday' },
    { id: 'osl-britton',               name: 'Britton',                          stage: 'Stage TBA', day: 'sunday' },
  ],
}

// ── Exports ───────────────────────────────────────────────────────────────────

export const FESTIVALS: Festival[] = [LOLLAPALOOZA, OUTSIDE_LANDS]

export function getFestival(id: string): Festival | null {
  return FESTIVALS.find(f => f.id === id) ?? null
}

export function getArtistsByDay(festival: Festival, day: string): FestivalArtist[] {
  return festival.artists.filter(a => a.day === day)
}

export const LOCAL_STORAGE_KEY = 'gigl_festival_id'
